---
title: "exploratory"
author: "Kylie Newcomer"
format: html
---

```{r}
library(tidyverse)
library(knitr)
library(pscl)


smurf <- read_csv("data/PISCO_UCSB_subtidal_recruitment_fish_data.1.2.csv")

smurf_sp <- read_csv("data/PISCO_UCSB_subtidal_recruitment_fish_spp_list.1.2.csv")



# Data for ocean temperature and upwelling
ocean <- read_csv("data/ALL_OCEAN_DATA.csv")

```

## Exploring df
```{r}
recruits <- left_join(smurf, smurf_sp)


recruits$Date <- as.Date(paste(recruits$year, recruits$month, recruits$day, sep = "/"))
ocean$Date <- as.Date(ocean$Date, format = "%m/%d/%Y")

recruit_ocean <- left_join(recruits, ocean)
  

rf_yoy <- recruit_ocean %>% 
  filter(year >= 2012  &
        (month >= 2 & month <= 7)) %>% 
  filter(str_detect(site_code, "HAZ")| # Filter data for on Pelican and Hazards sample sites
            str_detect(site_code, "PEL")) %>% 
  filter(classcode == "KGBC" | classcode == "SCAR/SCAU" | classcode == "SATR") #KGB - SCAR/SCAU - SATR - PCLA

kb_yoy <- recruit_ocean %>% 
  filter((classcode == "PCLA") & 
           (year >= 2012) &
        (month >= 7 & month <= 11)) %>% 
  filter(str_detect(site_code, "HAZ")| # Filter data for on Pelican and Hazards sample sites
            str_detect(site_code, "PEL"))
  
      
  
summarized_yoy <- rf_yoy %>% 
  group_by(classcode, year) %>% 
  summarise(count = sum(total_fish_collected))


highest_rf <- recruits %>% 
  filter(genus == "Sebastes") %>% 
  group_by(classcode) %>% 
  summarise(count = sum(total_fish_collected)) %>% 
  filter(count >= 1000)

most_yoy <- highest_rf$classcode
```

```{r}
rf_yoy_av <- rf_yoy %>% 
  group_by(classcode, year) %>% 
  summarise(av_fish = mean(total_fish_collected)) %>% 
  ungroup()
```

```{r}
ggplot(rf_yoy_av, aes(year, av_fish)) +
  geom_line(aes(color = classcode))
```


```{r}
ggplot(rf_yoy, aes(month, total_fish_collected)) +
  geom_jitter(aes(color = classcode))
```


```{r}
ggplot(kb_yoy, aes(month, total_fish_collected)) +
  geom_jitter()

```
```{r}
for(i in seq_along(rf_yoy)){
  if (rf_yoy$total_fish_collected[i] >= 1)
    {rf_yoy$success[i] <- 1}
    else
      {rf_yoy$success[i] <- 0}
}
```


## Statistical analysis

FishPresence ~ binomial(1, p)
$$
logit(p) = B0 + B1 * SST
$$
```{r}
B0 <- 3
B1 <- -0.1


logit_p <- B0 + B1 * x

p <- exp(logit_p) / 
  (1 + exp(logit_p))

# Simulate presences and absence
success <- rbinom(n = 1000, size = 1, prob = p)
```

Fishcount ~ NegativeBinomial(r, p)
$$
log(p) = B2 + B3 * SST
$$
```{r}
B2 <- 2
B3 <- 0.1

log_mu <- B2 + B3 * x
mu <- exp(log_mu)

# Simulate count data
count <- rnbinom(n = 1000, size = 1.5, mu = mu)
```


```{r}
rf_presence_model <- glm(success ~ SST_D30 + beuti_30,  # formula: response ~ resp
                   data = rf_yoy, # data remains unchanged
                   family = binomial(link = "logit"))

summary(rf_presence_model)
```

```{r}
x <- seq(min(rf_yoy$SST_D30),max(rf_yoy$SST_D30), length.out = 1)


B0 <- 3
B1 <- -0.1


logit_p <- B0 + B1 * x

p <- exp(logit_p) / 
  (1 + exp(logit_p))

# Simulate presences and absence
success <- rbinom(n = 1000, size = 1, prob = p)

B2 <- 2
B3 <- 0.1

log_mu <- B2 + B3 * x
mu <- exp(log_mu)

# Simulate count data
count <- rnbinom(n = 1000, size = 1.5, mu = mu)


# Create actual count (factor in successes and failures)
actual_count <- success * count


simulated_data <- as_tibble(expand_grid(x, actual_count))

simulated_success <- as_tibble(expand_grid(x, success))

ggplot(simulated_data, aes(x, actual_count)) +
  geom_point()
```

```{r}
glm(success ~ x,
    data = simulated_success,
    family = binomial(link = "logit"))
```


Using 
```{r}
mod.hurdle <- hurdle(total_fish_collected ~ SST_D30, 
                     data = rf_yoy, 
                     dist = "negbin", 
                     zero.dist = "binomial",
                     link = "logit")

summary(mod.hurdle)
```

## generating 0 and 1s
```{r}

```

BEUTI

SST
